[build]
  publish = "public"
  command = "hugo --gc --minify"
  
[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"

[[redirects]]
  from = "/index_e.php"
  to = "/"

[[redirects]]
  from = "/donate_e.php"
  to = "/donate/"

[[redirects]]
  from = "/download_e.php"
  to = "/download/"

[[redirects]]
  from = "/topspeed_e.php"
  to = "/topspeed/"

[[redirects]]
  from = "/topspeed2_e.php"
  to = "/topspeed2/"

[[redirects]]
  from = "/topspeed3_e.php"
  to = "/topspeed3/"

[[redirects]]
  from = "/links_e.php"
  to = "/links/"